name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        working-directory: ./back
        run: npm ci

      - name: Build Backend
        working-directory: ./back
        run: npm run build

      - name: Install Frontend Dependencies
        working-directory: ./front
        run: npm ci

      - name: Build Frontend
        working-directory: ./front
        run: npm run build
